### PR TITLE
[Do not merge] Feature/Error objects

### LINKED ISSUE #61: Result object should include error objects instead of strings

### PR DESCRIPTION
**Pull request by friedger**
This PR
* replaces the string error with a proper object of type `ResultError` that has property code, message and parameter. A code can be one of the enum `ErrorCode`.
* uses the blockstack.js file from feature/error_messages (https://github.com/blockstack/blockstack.js/commit/17d7f45c2ac1c49f8abbc378fa13b951646a76d49)
* fixes #61

### CODE REVIEW

**Comment by friedger** [comment]
The blockstack.js file is patch to make the integration tests work, see https://github.com/blockstack/blockstack.js/issues/514

**Comment by larrysalibra** [comment]
Thanks for this @friedger - i'm not going to get a chance to review this until next week. Have a great vacation!

**Comment by shreyasthiagaraj** [comment]
@friedger these changes look good to me. Please fix conflicts though.

**Comment by friedger** [comment]
It needs merging in blockstack.js first

**Comment by friedger** [comment]
Depends on merging feature branch error_messages into storage_strategies in blockstack.js

**Comment by friedger** [comment]
New PR for this issue is #161

**Pull request closed without merging**
