### PR TITLE
[Documentation] Handle blockstack sessions

### PR DESCRIPTION
**Pull request by friedger**
This PR 
* adds a section about handling blockstack sessions highlighting the need for singleLaunch mode and explaining app links

related to #83 and https://forum.blockstack.org/t/blockstack-sign-in-from-android-application/6163

### CODE REVIEW

**Comment by moxiegirl** [comment]
@larrysalibra you agree with this?

**Comment by moxiegirl** [comment]
I'll likely move this into the docs directory at some point.  IOW, we might need something more than the tutorial at some point.

**Comment by friedger** [comment]
@moxiegirl Yes, I would like to a developer guide like on https://developer.android.com/guide/ just simpler and in the docs folder.

**Comment by moxiegirl** [comment]
@friedger I'll review that example site.  This is certainly something we can work toward.  I've got a couple of things in the queue ahead.  I'll create an issue for this work.

**Pull request merged**
